# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\users\rlawl\Desktop\정보입력.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(378, 304)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name = QtWidgets.QLabel(Frame)
        self.name.setGeometry(QtCore.QRect(50, 30, 30, 30))
        self.name.setObjectName("name")
        self.addr = QtWidgets.QLabel(Frame)
        self.addr.setGeometry(QtCore.QRect(50, 70, 30, 30))
        self.addr.setObjectName("addr")
        self.hp = QtWidgets.QLabel(Frame)
        self.hp.setGeometry(QtCore.QRect(30, 110, 50, 30))
        self.hp.setObjectName("hp")
        self.id = QtWidgets.QLabel(Frame)
        self.id.setGeometry(QtCore.QRect(30, 150, 50, 30))
        self.id.setObjectName("id")
        self.car_id = QtWidgets.QLabel(Frame)
        self.car_id.setGeometry(QtCore.QRect(30, 190, 50, 30))
        self.car_id.setObjectName("car_id")
        self.ok_calcel = QtWidgets.QDialogButtonBox(Frame)
        self.ok_calcel.setGeometry(QtCore.QRect(120, 250, 193, 28))
        self.ok_calcel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_calcel.setObjectName("ok_calcel")
        self.name_edit = QtWidgets.QLineEdit(Frame)
        self.name_edit.setGeometry(QtCore.QRect(100, 30, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name_edit.setFont(font)
        self.name_edit.setMaxLength(10)
        self.name_edit.setObjectName("name_edit")
        self.add_edit = QtWidgets.QLineEdit(Frame)
        self.add_edit.setGeometry(QtCore.QRect(100, 70, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.add_edit.setFont(font)
        self.add_edit.setText("")
        self.add_edit.setMaxLength(45)
        self.add_edit.setObjectName("add_edit")
        self.hp1_edit = QtWidgets.QLineEdit(Frame)
        self.hp1_edit.setGeometry(QtCore.QRect(170, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.hp1_edit.setFont(font)
        self.hp1_edit.setMaxLength(4)
        self.hp1_edit.setObjectName("hp1_edit")
        self.hp2_edit = QtWidgets.QLineEdit(Frame)
        self.hp2_edit.setGeometry(QtCore.QRect(260, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.hp2_edit.setFont(font)
        self.hp2_edit.setMaxLength(4)
        self.hp2_edit.setObjectName("hp2_edit")
        self.id1_edit = QtWidgets.QLineEdit(Frame)
        self.id1_edit.setGeometry(QtCore.QRect(100, 150, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.id1_edit.setFont(font)
        self.id1_edit.setMaxLength(6)
        self.id1_edit.setObjectName("id1_edit")
        self.id2_edit = QtWidgets.QLineEdit(Frame)
        self.id2_edit.setGeometry(QtCore.QRect(240, 150, 16, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.id2_edit.setFont(font)
        self.id2_edit.setMaxLength(1)
        self.id2_edit.setObjectName("id2_edit")
        self.car_id1_edit = QtWidgets.QLineEdit(Frame)
        self.car_id1_edit.setGeometry(QtCore.QRect(100, 190, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.car_id1_edit.setFont(font)
        self.car_id1_edit.setMaxLength(2)
        self.car_id1_edit.setObjectName("car_id1_edit")
        self.car_id2_edit = QtWidgets.QLineEdit(Frame)
        self.car_id2_edit.setGeometry(QtCore.QRect(150, 190, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.car_id2_edit.setFont(font)
        self.car_id2_edit.setMaxLength(2)
        self.car_id2_edit.setObjectName("car_id2_edit")
        self.car_id3_edit = QtWidgets.QLineEdit(Frame)
        self.car_id3_edit.setGeometry(QtCore.QRect(200, 190, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.car_id3_edit.setFont(font)
        self.car_id3_edit.setMaxLength(6)
        self.car_id3_edit.setObjectName("car_id3_edit")
        self.car_id4_edit = QtWidgets.QLineEdit(Frame)
        self.car_id4_edit.setGeometry(QtCore.QRect(320, 190, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.car_id4_edit.setFont(font)
        self.car_id4_edit.setMaxLength(2)
        self.car_id4_edit.setObjectName("car_id4_edit")
        self.num_010 = QtWidgets.QLabel(Frame)
        self.num_010.setGeometry(QtCore.QRect(110, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.num_010.setFont(font)
        self.num_010.setObjectName("num_010")
        self.desh1 = QtWidgets.QLabel(Frame)
        self.desh1.setGeometry(QtCore.QRect(240, 110, 16, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.desh1.setFont(font)
        self.desh1.setObjectName("desh1")
        self.desh2 = QtWidgets.QLabel(Frame)
        self.desh2.setGeometry(QtCore.QRect(220, 150, 16, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.desh2.setFont(font)
        self.desh2.setObjectName("desh2")
        self.blank = QtWidgets.QLabel(Frame)
        self.blank.setGeometry(QtCore.QRect(260, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.blank.setFont(font)
        self.blank.setObjectName("blank")
        self.desh3 = QtWidgets.QLabel(Frame)
        self.desh3.setGeometry(QtCore.QRect(135, 190, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.desh3.setFont(font)
        self.desh3.setObjectName("desh3")
        self.desh4 = QtWidgets.QLabel(Frame)
        self.desh4.setGeometry(QtCore.QRect(185, 190, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.desh4.setFont(font)
        self.desh4.setObjectName("desh4")
        self.desh5 = QtWidgets.QLabel(Frame)
        self.desh5.setGeometry(QtCore.QRect(305, 190, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.desh5.setFont(font)
        self.desh5.setObjectName("desh5")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.name.setText(_translate("Frame", "이름"))
        self.addr.setText(_translate("Frame", "주소"))
        self.hp.setText(_translate("Frame", "전화번호"))
        self.id.setText(_translate("Frame", "주민번호"))
        self.car_id.setText(_translate("Frame", "면허번호"))
        self.num_010.setText(_translate("Frame", "010 -"))
        self.desh1.setText(_translate("Frame", "-"))
        self.desh2.setText(_translate("Frame", "-"))
        self.blank.setText(_translate("Frame", "XXXXXX"))
        self.desh3.setText(_translate("Frame", "-"))
        self.desh4.setText(_translate("Frame", "-"))
        self.desh5.setText(_translate("Frame", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

